### PR TITLE
RACSignal+Operations: Dispose of previous signal in switchToLatest.

### PR DESCRIPTION
**Pull request by Shachlan**
This fix fixes an issue in switchToLatest that allows for the previous
signal to send a value even after a new signal is sent. The source of
the issue is the 2 subscriptions on connection.signal, and the fact
that nothing enforces that one will terminate before the next one
continue.
This ensures that the previous subscription's disposable will be
disposed before any effect from the current signal will be sent to the
subscriber.

### CODE REVIEW

**Comment by Shachlan** [comment]
@StatusReport, not sure where to add new tests.

**Comment by StatusReport** [comment]
@Shachlan can you please check whether [this](https://github.com/Lightricks/ReactiveCocoa/commit/0dd557ef613ce4da72dcf7610d479d49642891b7) works for you as well?

**Comment by Shachlan** [comment]
@StatusReport, it works, except for the minor issue that it raises when the received signal is nil, unlike the current implementation.

**Comment by Shachlan** [comment]
And I see that BarakY already mentioned that :).

**Comment by StatusReport** [comment]
Closing in favor of #24.

**Pull request closed without merging**
