### PR TITLE
ReactiveObjC: Add `rac` prefix to excobjc macros.

### PR DESCRIPTION
**Pull request by barakwei**

### CODE REVIEW

**Comment by StatusReport** [comment]
LGTM. Note that `metamacros.h` have overlapping macros as well.

**Comment by barakwei** [comment]
I don't have a real solution for `metamacros.h` except prefixing with `rac_` again. at least it's somewhat protected with the `undef` but if you wish to extend the limit to 80 items, that will be a problem.

**Comment by StatusReport** [comment]
Well, theoretically because of the `undef`s (that should exist in `EXTScope.h` as well for private macros, btw, since it's a header file) it should work, but there's an issue with precompiled headers that causes the compiler to emit warnings about multiple definitions of these macros.

Prefixing doesn't seem like a very bad solution then, but let's postpone it until we have real issues with these macros.

**Comment by barakwei** [comment]
Everything is true unless we change our `metamacro.h` file. Anyway, I agree about postponing this.
I didn't saw a warning with precompiled errors about these.
Just note that we used macros in `EXTScope.h` b/c the headers guards didn't import the one in RAC, but since `metamacro.h` doesn't have header guards, most projects use the file in RAC.

**Comment by StatusReport** [comment]
Fun :)

**Pull request merged**
