### PR TITLE
ReactiveObjC.xcodeproj: do not analyze on build.

### PR DESCRIPTION
**Pull request by barakwei**

### CODE REVIEW

**Comment by StatusReport** [comment]
It should be `NO` by default. Why am I seeing it as an addition and not modification?

**Comment by barakwei** [comment]
Their .xcconfig file sets it to YES

**Comment by StatusReport** [comment]
I just configured CircleCI to build from forks. Can you update this PR so it'll test?

**Comment by barakwei** [comment]
All green. Want me to update circle.yml's xcode version?

**Comment by StatusReport** [comment]
Yeah, but let's do it in a separate PR.

**Comment by barakwei** [comment]
10-4

**Pull request merged**
