### PR TITLE
RACSignal+Operations: add -[RACSignal retry:when:]..

### PR DESCRIPTION
**Pull request by DekelAvrahami**
Add a retry method that allows quitting the retry sequence as a result
of the raised error.

### CODE REVIEW

**Comment by StatusReport** [comment]
Seems like this is called `retryWhen` in [ReactiveX parlance](http://reactivex.io/documentation/operators/retry.html). Any reason not to use the same naming?

**Comment by DekelAvrahami** [comment]
Fixed and squashed.

**Comment by StatusReport** [comment]
Who should review this?

**Comment by barakyoresh** [comment]
Fancy. The lazy cunts didn't add tests for `retry`, even though there are tests for all other operators. I'm guessing it's because counting subscribers is a bit of a pain (see how LLReactiveMatchers did it). You could implement it just for the test with a dynamic signal, a `__block NSUInteger subscribeCount`, and a `__block void (^errorBlock)(NSError *)`. I leave it to you to decide whether that's needed or not. If you decide not to - just merge.

**Review by byohay — APPROVED** [review]

**Pull request merged**
